books/apps/book/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    # 图书操作页面
    re_path('(?P<condition>detail|buy|rent|shop|order)/(?P<pk>\d+)/', views.BookAPIView.as_view()),
    # re_path('category/(?P<pk>\d+)/', views.CategoryAPIView.as_view()),
    # re_path('tag/(?P<pk>\d+)/', views.TagAPIView.as_view()),
    # 代码冗余，所以和为下面的一个方法
    re_path('(?P<condition>category|tag)/(?P<pk>\d+)/', views.CaTaAPIView.as_view()),
    re_path('(?P<condition>author|book)/(?P<pk>\d+)/', views.AuthorAPIView.as_view()),
    re_path(r'^search/', include('haystack.urls')),
]

books/apps/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('msg/', views.SMSAPIView.as_view()),
    path('', views.Home.as_view()),

]

books/apps/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginAPIView.as_view()),
    path('register/', views.RegisterAPIView.as_view()),
    path('logout/', views.LogoutAPIView.as_view()),
    path('sms/', views.SMSAPIView.as_view()),
    path('password/', views.PasswordAPIView.as_view()),
    path('avatar/', views.AvatarAPIView.as_view()),
    path('info/', views.InfoAPIView.as_view()),
    path('order/', views.OrderAPIView.as_view()),
    path('rent/', views.RentAPIView.as_view()),
    path('message/', views.MessageAPIView.as_view()),
    path('edit/', views.EditAPIView.as_view()),
    path('shop/delete/', views.DeleteBook.as_view()),
    path('rent/delete/', views.DeleteRent.as_view()),
    path('shop/', views.ShopAPIView.as_view()),
    path('codes/', views.get_code),
    path('settle/', views.SettleAPIView.as_view()),


]

books/urls.py
from django.urls import re_path, path, include
import xadmin
xadmin.autodiscover()
from xadmin.plugins import xversion
xversion.register_models()
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path(r'xadmin/', xadmin.site.urls),
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),  # 这是media用户上传文件路由
    path('user/', include('user.urls')),
    path('book/', include('book.urls')),
    path('order/', include('order.urls')),
    # path('docs/', include_docs_urls(title='站点页面标题')),
    path('', include('home.urls')),
]

books/apps/book/models.py
from django.db import models
from user.models import RentHistory, Order, User
# from user.models import


# 图书详情表
class Book(models.Model):
    author = models.ManyToManyField(to='Author', related_name='books', db_constraint=False)
    user = models.ForeignKey(to=User, db_constraint=False, on_delete=models.DO_NOTHING,
                             related_name='books', null=True, blank=True)
    category = models.ForeignKey(to='Category', db_constraint=False, on_delete=models.DO_NOTHING,
                                 related_name='books', null=True, blank=True)
    rent = models.ForeignKey(to=RentHistory, db_constraint=False, on_delete=models.DO_NOTHING,
                             related_name='books', null=True, blank=True)
    order = models.ForeignKey(to=Order, db_constraint=False, on_delete=models.DO_NOTHING,
                              related_name='books', null=True, blank=True)
    name = models.CharField(max_length=64, verbose_name='书名')
    image = models.ImageField(upload_to='static/img/', verbose_name='封面', blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=3, verbose_name='租书价格', default=0)
    amount = models.IntegerField(verbose_name='可借数量', default=0)
    publish_date = models.DateField(verbose_name='出版日期')
    pages = models.IntegerField(verbose_name='书籍页数')
    stars = models.DecimalField(max_digits=3, decimal_places=2, verbose_name='推荐指数')
    desc = models.CharField(max_length=255, verbose_name='书本简介')
    b_money = models.DecimalField(max_digits=4, decimal_places=2, verbose_name='所需押金', null=True, blank=True)
    buy_price = models.DecimalField(max_digits=8, decimal_places=3, verbose_name='购买价格', null=True, blank=True)
    publishers = models.CharField(max_length=64, verbose_name='出版社')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'book'
        verbose_name = '图书表'
        verbose_name_plural = verbose_name

    @property
    def author_detail(self):
        authors = self.author.all()
        author_list = []
        for author in authors:
            dic = {'name': author.name, 'info': author.info, 'image': author.image}
            author_list.append(dic)
        return author_list

    @property
    def user_detail(self):
        users = self.user.objects.all()
        user_list = []
        for user in users:
            dic = {'name': user.username, 'phone': user.phone, 'score': user.score, 'sex': user.sex,
                   'avatar': user.avatar}
            user_list.append(dic)
        return user_list

    @property
    def category_detail(self):
        categorys = self.category.objects.all()
        category_list = []
        for category in categorys:
            dic = {'name': category.get_name_display()}
            category_list.append(dic)
        return category_list

    @property
    def tag_detail(self):
        tags = self.tag.all()
        tag_list = []
        for tag in tags:
            dic = {'name': tag.get_name_display()}
            tag_list.append(dic)
        return tag_list

    @property
    def rent_detail(self):
        rents = self.rent.objects.all()
        rent_list = []
        for rent in rents:
            dic = {'amount': rent.amount, 'rent_time': rent.rent_time, 'back_time': rent.back_time}
            rent_list.append(dic)
        return rent_list

    @property
    def order_detail(self):
        orders = self.order.objects.all()
        order_list = []
        for order in orders:
            dic = {'amount': order.amount, 'order_time': order.order_time, 'user': order.user.username}
            order_list.append(dic)
        return order_list


# 作者表
class Author(models.Model):
    name = models.CharField(max_length=64, verbose_name='作者姓名')
    info = models.CharField(max_length=255, verbose_name='作者简介', null=True, blank=True)
    image = models.ImageField(default='static/img/name.png', upload_to='static/img/', verbose_name='作者图片')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'author'
        verbose_name = '作者表'
        verbose_name_plural = verbose_name

    @property
    def book_detail(self):
        books = self.books.all()
        book_list = []
        for book in books:
            dic = {'name': book.name, 'desc': book.desc, 'pages': book.pages, 'publishers': book.publishers,
                   'image': book.image, 'stars': book.stars, 'amount': book.amount, 'price': book.price, 'id': book.id}
            book_list.append(dic)
        return book_list


# 分类表
class Category(models.Model):
    cate_type = (
        (1, '中国文学'),
        (2, '外国文学'),
    )
    name = models.IntegerField(choices=cate_type, verbose_name='图书分类', default=1)

    def __str__(self):
        return self.names

    class Meta:
        db_table = 'book_category'
        verbose_name = '图书分类表'
        verbose_name_plural = verbose_name

    @property
    def names(self):
        return self.get_name_display()

    @property
    def book_detail(self):
        books = self.books.all()
        book_list = []
        for book in books:
            dic = {'name': book.name, 'desc': book.desc, 'pages': book.pages, 'publish_date': book.publish_date,
                   'image': book.image, 'stars': book.stars, 'id': book.id}
            book_list.append(dic)
        return book_list


# 标签表
class Tags(models.Model):
    cate_type = (
        (1, '文学类'),
        (2, '流行'),
        (3, '文化'),
        (4, '生活'),
        (5, '经管'),
        (6, '科技')
    )
    name = models.IntegerField(choices=cate_type, verbose_name='书籍标签')
    book = models.ManyToManyField(to='Book', related_name='tag', db_constraint=False)

    def __str__(self):
        return self.names

    class Meta:
        db_table = 'home_tags'
        verbose_name = '标签表'
        verbose_name_plural = verbose_name

    @property
    def names(self):
        return self.get_name_display()

    @property
    def book_detail(self):
        books = self.book.all()
        book_list = []
        for book in books:
            dic = {'name': book.name, 'desc': book.desc, 'pages': book.pages, 'publish_date': book.publish_date,
                   'image': book.image, 'stars': book.stars, 'id': book.id}
            book_list.append(dic)
        return book_list


# 加入购物车
class BookCart(models.Model):
    user = models.ForeignKey(to=User, db_constraint=False, on_delete=models.DO_NOTHING, related_name='cart')
    book = models.ForeignKey(to='Book', db_constraint=False, on_delete=models.DO_NOTHING, related_name='cart')
    amount = models.IntegerField(verbose_name='购买数量')

    def __str__(self):
        return self.book.name

    class Meta:
        verbose_name = '购物车表'
        verbose_name_plural = verbose_name

    # @property
    # def book_detail(self):  # 一对多的一方，点all拿不到所以可以直接使用外键
    #     print(12221)
    #     books = self.book
    #     print(books)
    #     book_list = []
    #     for book in books:
    #         dic = {'name': book.name, 'image': book.image, 'buy_price': book.buy_price, 'id': book.pk,
    #                'price': book.amount*book.buy_price}
    #         book_list.append(dic)
    #     return book_list

    # @property
    # def user_detail(self):  # 错误信息同上
    #     print(111)
    #     users = self.user.objects.all()
    #     print(users)
    #     user_list = []
    #     for user in users:
    #         dic = {'id': user.pk, 'name': user.username}
    #         user_list.append(dic)
    #     return user_list


# 用户租借（是否在线租借字段）
class Rent(models.Model):
    book = models.ForeignKey(to=Book, db_constraint=False, on_delete=models.DO_NOTHING, related_name='rented')
    user = models.ForeignKey(to=User, db_constraint=False, on_delete=models.DO_NOTHING, related_name='rented')
    amount = models.IntegerField(verbose_name='租借数量', default=0)
    rent_time = models.DateTimeField(auto_now_add=True, verbose_name='租书日期')
    back_time = models.DateField(null=True, verbose_name='还书日期')
    # 租书时间
    max_time = models.IntegerField(default=30)

    class Meta:
        db_table = 'book_rent'
        verbose_name = '租借'
        verbose_name_plural = verbose_name


class Ordered(models.Model):
    book = models.ForeignKey(to='Book', db_constraint=False, on_delete=models.DO_NOTHING, related_name='ordered')
    user = models.ForeignKey(to=User, db_constraint=False, on_delete=models.DO_NOTHING, related_name='ordered')
    amount = models.IntegerField(verbose_name='租借数量', default=0)
    a_money = models.DecimalField(max_digits=8, decimal_places=3, verbose_name='预约价格', default=0)
    order_time = models.DateTimeField(auto_now_add=True, verbose_name='预约日期')

    class Meta:
        db_table = 'book_ordered'
        verbose_name = '预约'
        verbose_name_plural = verbose_name

books/apps/home/models.py
from django.db import models

# Create your models here.

books/apps/book/views.py
from django.shortcuts import render,redirect
from rest_framework.views import APIView
from . import models
from . import serializers
from books.libs.wrap import login_auth
from django.utils.decorators import method_decorator
from rest_framework.response import Response
# Create your views here.



# 图书详情页|购买|租借
@method_decorator(login_auth, name='get')
class BookAPIView(APIView):
    """
       返回所有图书信息.
       """
    def get(self, request, *args, **kwargs):
        if kwargs['condition'] == 'detail':  # 详情
            book_obj = models.Book.objects.all().filter(pk=kwargs['pk'])
            book = serializers.BookDetailSerai(instance=book_obj, many=True).data
            # print(book)
            return render(request, 'book/bookdetail.html', locals())
        elif kwargs['condition'] == 'buy':
            id = kwargs['pk']
            cart_obj = models.BookCart.objects.filter(book_id=id).first()
            if cart_obj:
                cart_obj.amount += 1
                cart_obj.save()
            else:
                models.BookCart.objects.create(book_id=id, user_id=request.user.id, amount=1)
            carts = models.BookCart.objects.filter(book_id=id)
            return render(request, 'user/shop.html', locals())
        elif kwargs['condition'] == 'rent':  # 租借
            rent_obj = models.Rent.objects.filter(book_id=kwargs['pk']).first()
            if rent_obj:
                rent_obj.amount += 1
                rent_obj.save()
            else:
                models.Rent.objects.create(book_id=kwargs['pk'], user_id=request.user.id, amount=1)
            rent = models.Rent.objects.filter(book_id=kwargs['pk'])
            return render(request, 'user/rent.html', locals())
        elif kwargs['condition'] == 'order':  # 预约
            order_obj = models.Ordered.objects.filter(book_id=kwargs['pk']).first()
            if order_obj:
                order_obj.amount += 1
                order_obj.save()
            else:
                models.Ordered.objects.create(book_id=kwargs['pk'], user_id=request.user.id, amount=1)
            orders = models.Ordered.objects.filter(book_id=kwargs['pk'])
            return render(request, 'user/order.html', locals())
        else:  # 加入购物车页面
            pk = kwargs['pk']
            books = models.BookCart.objects.filter(book_id=pk).first()
            if books:
                books.amount += 1
                books.save()
            else:
                models.BookCart.objects.create(amount=1, user_id=request.user.id, book_id=pk)
            # return redirect('/home')

            return Response({
                'start': 100,
                'msg': 'ok',
            })


# 作者详情、作者书籍页面
@method_decorator(login_auth, name='get')
class AuthorAPIView(APIView):
    """
       返回所有图书信息.
       """
    def get(self, request, *args, **kwargs):
        # print(kwargs)
        author_obj = models.Author.objects.all().filter(pk=kwargs['pk']).first()
        # print(cate_obj)
        author = serializers.AuthorModelSerializer(instance=author_obj).data
        # print(author)
        if kwargs['condition'] == 'author':
            # print(author['name'])
            return render(request, 'author/detail.html', locals())
        else:  # 书籍页面
            return render(request, 'author/book.html', locals())


# 标签详情页|分类详情页面
@method_decorator(login_auth, name='get')
class CaTaAPIView(APIView):
    """
       返回所有图书信息.
       """
    def get(self, request, *args, **kwargs):
        # print(kwargs)
        if kwargs['condition'] == 'category':
            cate_obj = models.Category.objects.all().filter(name=kwargs['pk']).first()
            # print(cate_obj)
            category = serializers.CategoryModelSerializer(instance=cate_obj).data
            # print(category)
            return render(request, 'book/category.html', locals())
        else:
            tag_obj = models.Tags.objects.all().filter(name=kwargs['pk']).first()
            tags = serializers.TagModelSerializer(instance=tag_obj).data
            # print(tags)
            return render(request, 'book/tag.html', locals())

books/apps/home/views.py
from django.shortcuts import render, HttpResponse, redirect
from books.settings import constant
from rest_framework.views import APIView
from book.serializers import BookModelSerializer, TagModelSerializer, CategoryModelSerializer, AuthorModelSerializer
from user.serializers import UserModelSerializer, RentHisModelSerializer, OrderModelSerializer
from book.models import Book, Author, Tags, Category, User, RentHistory, Order
import re
import random
from django.core.cache import cache
from books.libs.yuntongxun import send_sms
from rest_framework.response import Response
# Create your views here.


# 主页面
# @method_decorator(login_auth, name='get')
class Home(APIView):
    """
       返回所有图书信息.
       """
    def get(self, request, *args, **kwargs):
        book_obj = Book.objects.all()
        book_list = BookModelSerializer(instance=book_obj, many=True).data
        tag_obj = Tags.objects.all()
        tags_list = TagModelSerializer(instance=tag_obj, many=True).data
        author_obj = Author.objects.all()[4:8]
        author_list = AuthorModelSerializer(instance=author_obj, many=True).data
        category_obj = Category.objects.all()
        category_list = CategoryModelSerializer(instance=category_obj, many=True).data
        # 轮播图单个页面渲染
        i = book_list[:3]
        m = book_list[3:6]
        n = book_list[6:9]
        p = book_list[9:12]
        q = book_list[12:15]
        # 前端标签渲染
        d = book_list[11:15]
        x = book_list[15:19]

        return render(request, 'home.html', locals())


# 短信发送接口
class SMSAPIView(APIView):
    """
       返回所有图书信息.
       """
    def post(self, request, *args, **kwargs):
        print(request.data)
        mobile = request.data.get('username')
        if not mobile:
            return Response({
                'status': 400,
                'msg': 'mobile参数是必须的'
            })
        # 后台要多mobile数据进行安全校验
        if not re.match(r'^1[3-9]\d{9}$', mobile):
            return Response({
                'status': 300,
                'msg': '手机号有误'
            })
        # # 生成随机的验证码
        code = ''
        for i in range(6):
            code += str(random.randint(0, 9))
        # redis 存储
        cache.set(mobile, code, constant.SMS_EXPIRE_TIME)
        # 调用短信第三方发送短信
        result = send_sms('17621948046', (code, constant.SMS_EXPIRE_TIME), 1)
        if not result:
            return Response({
                'status': 200,
                'result': '短信发送失败'
            })
        return Response({
            'status': 100,
            'result': '短信发送成功'
        })

books/templates/user/alipay.html
{% extends 'home.html' %}
{% block main %}
    <div>支付成功</div>
{% endblock %}

books/templates/user/message.html
{% extends 'home.html' %}
{% block main %}
    <div class="container" style="margin-top: 100px;margin-bottom: 400px">
        <br>
        <br>
        <h2 style="text-align: center">个人信息主页</h2>
        <br>
        <br>

        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                <table class="table">
                    <thead>
                    <tr>
                        <th>用户名</th>
                        <th>地址</th>
                        <th>身份证号</th>
                        <th>电话</th>
                        <th>个性签名</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in user %}
                        <tr class="success">
                            <td>{{ i.username }}</td>
                            <td>{{ i.address }}</td>
                            <td>{{ i.idcard }}</td>
                            <td>{{ i.phone }}</td>
                            <td>{{ i.info }}</td>
                            <td>
                                <a href="/user/edit" class="btn btn-success">修改信息</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% include 'footer.html' %}
    </div>

{% endblock %}

books/templates/user/rent.html
{% extends 'home.html' %}
{% block main %}
    <link rel="stylesheet" href="/static/css/shop.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <div class="container" style="margin-top: 200px;margin-bottom: 500px">
        <div class="row">
            <ul class="cart_list_th clearfix">
                <li class="col01" style="text-align: left;margin-left: 1%"><span style="left: 0">全选</span></li>
                <li class="col01">书本名称</li>
                <li class="col02">书本图片</li>
                <li class="col03">租借价格</li>
                <li class="col04">租借数量</li>
                <li class="col05">借阅天数</li>
                <li class="col06">其他操作</li>
            </ul>
            {% for book in rent %}
                <ul class="cart_list_td clearfix" id="{{ book.book.id }}">
                    <li class="col01" style="margin:1px auto">
                        <input id=d{{ forloop.counter0 }} class="sum"
                               onclick="funa({{ book.book.id }},{{ book.amount }},{{ book.book.price }},{{ book.max_time }})"
                               type="checkbox" name>
                    </li>
                    <li class="col03"></li>
                    <li class="col04">{{ book.book.name }}</li>
                    <li class="col02"><img src="/static/{{ book.book.image }}"></li>
                    <li class="col05">{{ book.book.price }}元/天</li>
                    <li class="col06">
                        <div class="num_add">
                            <a onclick="subtraction(1,{{ book.book.id }},{{ book.book.price }},{{ book.amount }},{{ book.max_time }})"
                               price="{{ book.book.price }}" class="add fl">+</a>
                            <input id="{{ book.book.id }}" type="text" class="num_show fl" value="{{ book.amount }}"
                                   disabled>
                            <a onclick="subtraction(-1,{{ book.book.id }},{{ book.book.price }},{{ book.amount }},{{ book.max_time }})"
                               price="{{ book.book.price }}" class="minus fl">-</a>
                        </div>
                    </li>
                    <li class="col07">{{ book.max_time }}/天</li>
                    <li class="col08"><a onclick="fun({{ book.book.id }})">删除</a></li>
                </ul>
            {% empty %}
                <ul class="cart_list_td clearfix" id="{{ book.book.id }}">
                    <li class="col01"><input id="id_book" onclick="is_select(7)" type="checkbox" name=""></li>
                    <li class="col03"></li>
                    <li class="col04">无数据</li>
                    <li class="col02"><img src="/static/{{ book.book.image }}"></li>
                    <li class="col05">无数据</li>
                    <li class="col06">
                        <div class="num_add">
                            <a onclick="add_cart(7)" href="javascript:;" class="add fl">+</a>
                            <input id="num_show_7" type="text" class="num_show fl" value="0">
                            <a onclick="sub_cart(7)" href="javascript:;" class="minus fl">-</a>
                        </div>
                    </li>
                    <li class="col07">0元</li>
                    <li class="col08"><a href="">删除</a></li>
                </ul>
            {% endfor %}
            <ul class="settlements">
                <li class="col01"><input type="checkbox" name="" checked="" value=""></li>
                <li class="col02">全选</li>
                <li class="col03 money">
                    合计(不含运费)：<span>¥</span><em id="ems">元</em><br>共计<b id="shop">0</b>件商品
                </li>
                <li class="col04"><a id="go_money">去结算</a></li>
            </ul>
            <form action="">
                {% csrf_token %}
            </form>
        </div>

    </div>
    {% include 'footer.html' %}
    <script>
        let show = [];
        let lis2 = [];

        /* 用户点击小按钮的时候 */
        function funa(a, b, c, d) {
            /* 定义一个状态用来获取show中数据的索引 */
            let ins = '123';
            /* 判断show中是否有数据 */
            show.forEach(function (element, index) {
                if (element[0] == a) {
                    ins = index;
                }
            });
            let flag = false;
            let ins2 = "123";
            /* 通过循环lis2来拿到里面的数据，然后和用户传过来的数据进行对比，如果有说明用户点击的是取消 */
            lis2.forEach(function (element, index) {
                if (element[0] == a) {
                    /* 取消的时候直接将数据移除 */
                    lis2.splice(index, 1);
                    flag = true;
                }
            })
            /* 选中状态 */
            if (!flag) {
                /* 对show返回的ins进行判断，看show中是否有值 */
                if (ins === "123") {
                    /* show没有值，直接当前lis2添加就好  书id,书amount,书money,书租借天数 */
                    lis2.push([Number(a), Number(b), Number(c), Number(d)]);
                }
                /* 说明show中有值，那么就将show中的值同步到lis2中，通过show的索引拿到show的数据，lis2直接添加 */
                else {
                    lis2.push(show[ins]);
                }
            }
            /* 调用数据渲染的方法，直接渲染数 */
            count()
        }

        /* 页面数据渲染的方法 */
        let count = function () {
            let sum = 0;
            let amount = 0;
            /*
            页面数据渲染的时候，去lis2中找到数据，然后将数据循环出来，之后进行加减，lis2中的数据是用户点击的
            每一次的数据，点击一次就保存一次，或者取消一次
           */
            lis2.forEach(function (element, index) {
                /* cc是单个书本的总金额 -id,money,amount,time */
                cc = Number(element[1]) * Number(element[2])*Number(element[3]);
                /* sum是所有数据的金额 */
                sum += cc;
                /* 这个是所有的数据的个数 */
                amount += Number(element[1])
            });
            /* 然后找到这个标签，将数据渲染到对应的页面 */
            $(' #ems').html(sum);
            $('#shop').html(amount)
        };

        /* 加减算法的方法，参数分别是增量，id，价格，数量，天数*/
        function subtraction(a, b, c, d, e) {
            let flag = false;
            /* 是否选中状态 */
            let ind = '';
            /* 存储选中状态的索引 */
            /*
             第一步，先找到我要渲染的那个标签，因为是动态的，所以不能写死，所以我用到了字符串的替换
             $('#%s'.replace('%s',b)) 后面的数据是我要替换的那个东西的id，这样子就可以做到动态的查找标签
             */
            let xxx = $("#%s".replace('%s', b));
            /* 第二步，判断我存储用户点击数据的数组中是否有当前的id，定义两个变量用来接收选中状态和数据的索引*/
            /* a增量，bid，c价格，d数量，e天数 */
            lis2.forEach(function (element, index) {
                if (element[0] == b) {
                    flag = true;
                    ind = index
                }
            });
            /* 用户不在选中状态，直接修改show中的数据 */
            if (!flag) {
                /* 找到当前的那个input框的数据 */
                current_num = xxx.val();
                /* 让当前页面的数据+-用户点击的按钮，将结果给result这个变量存储 */
                /* 最终数量 */
                let result = Number(current_num) + Number(a);
                /*
                 result的结果有两种，第一种有值，第二种为0，为0的时候直接给用户弹出一个事件，告诉用户
                 数据最少是1，然后直接结束掉
                */
                if (!result) {
                    swal('数量最小为1！')
                    return
                }
                /* 否则的话，将当前的数据直接渲染到页面上，让用户看 */
                xxx.val(result);
                /* 接下来就是存储数据到show和lis2中，先判断两个列表中是否已经有当前的数据 */
                let flag4 = false;
                /* show的格式[id,amount,price] */
                show.forEach(function (element, index) {
                    /* 说明有这个数据，直接将他的数量更新 */
                    if (element[0] == b) {
                        /*？？？*/
                        element[1] = result;
                        flag4 = true
                    }
                });
                /* 这个是说明show里面没有当前用户点击的数据，那么就直接存储
                书id,书amount,书money,书租借天数
                a,bid，c价格，d数量，e天数
                 */
                if (!flag4) {
                    show.push([Number(b), result, Number(c),Number(e)])
                }
            }
            /* 用户在选中状态 */
            else {
                /* 获取当前页面的数据 */
                current_num = xxx.val();
                /* 用户点击后的最终数量 */
                let result = Number(current_num) + Number(a);
                /* 对最终数量进行判断 */
                if (!result) {
                    swal('数量最小为1！');
                    return
                }
                /* 渲染到页面 */
                xxx.val(result);
                let flag2 = false;
                /* 判断show中是否有这个数据 */
                /* 判断我的show中是否有当前这个数据 */
                show.forEach(function (element, index) {
                    if (element[0] == b) {
                        /* 有的时候，直接将最后的数据给show/ */
                        show[index][1] = result;
                        flag2 = true
                    }
                });
                /* 没有数据的时候，将数据添加到show中 */
                if (!flag2) {
                    show.push([Number(b), result, Number(c),Number(e)]);
                }
                /* show中有数据，将数据给lis2,让他渲染，因为我在选中状态 */
                lis2[ind][1] = result;
                /* 调用渲染数据的方法 */
                count()
            }
        }

        /* 删除事件 */
        function fun(a) {
            swal({
                title: "确定删除?",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    let str = '';
                    {#this.addClass("hidden")#}
                    if (willDelete) {
                        console.log(a)
                        /* 向后端发送数据，得用Ajax不然无法发送 */
                        $.ajax({
                            url: '/user/rent/delete/?id=' + a,
                            success: function (data) {
                                {#$("#%s".replace("%s",a)).addClass("hidden")#}
                                {# 移除标签 #}
                                lis2.forEach(function (element, index) {
                                    {#console.log(element,element[0],a)#}
                                    if (element[0] == data.book_id) {
                                        lis2.splice(index, 1)
                                    }
                                });
                                count()
                                /* 找到标签直接删除，不能直接删除，因为找不到标签 */
                                $("#%s".replace("%s", a)).remove()
                            }
                        })
                    }
                });
        }

        /* 结算事件 */
        $('#go_money').on('click', function () {
            let cartId = '';
            let bookAmount = '';
            lis2.forEach(function (element, index) {
                if (element) {
                    //console.log(element)
                    //console.log(element[0], element[1])
                    cartId = cartId+element[0]+','
                    bookAmount = bookAmount+element[1]+','
                }
            });
            //console.log(cartId);
            //console.log(bookAmount);
            $.ajax({
                url: '/user/settle/',
                type: 'post',
                data: {
                    'cartId': cartId,
                    'bookAmount': bookAmount,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    //alert('hahaha')
                    console.log(data)
                    window.location.href = data.url+'?cartId='+cartId
                }
            })
        })
    </script>
{% endblock %}